version: '3.7'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    environment:
      TZ: Asia/Tokyo
