version: '3.7'

services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - FLASK_ENV=development
    environment:
      TZ: Asia/Tokyo
