version: '3.7'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
