version: '3.7'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000
