apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
  labels:
    name: flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: docker build -t gcr.io/PROJECT_ID/hello-flask-app:latest
        env:
        - name: FLASK_ENV
          value: "development"
      restartPolicy: Always
